import Footer from "@/features/footer";
import { Header } from "@/features/header";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { Golos_Text } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";
import { Providers } from "../providers";
import "./globals.css";
import { getMessages } from "next-intl/server";

const golosText = Golos_Text({
  variable: "--font-golos-text",
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${golosText.variable} antialiased`}>
        <Providers locale={locale} messages={messages}>
          <Header />
          {children}
          <footer id="contacts">
            <Footer />
          </footer>
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
